# Generated by Django 5.0.1 on 2024-02-04 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otpverificationdata',
            options={'verbose_name': 'OTP manager', 'verbose_name_plural': 'OTP manager'},
        ),
        migrations.AddField(
            model_name='otpverificationdata',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otpverificationdata',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='otpverificationdata',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Admin', 'Admin'), ('Block Coordinator', 'Bc'), ('District Coordinator', 'Dc'), ('Volunteer', 'Volunteer')], default='Admin', max_length=30)),
                ('user_unique_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('fathers_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mothers_name', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_pic', models.ImageField(upload_to='profile/images/%y/%b/')),
                ('address', models.CharField(blank=True, max_length=80, null=True)),
                ('pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('flag_course_done', models.BooleanField(default=False)),
                ('flag_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.masterblockdata')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.masterdistrictdata')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teammate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
